## Importações e Subindo os dados

In [1]:
# from google.colab import auth
# auth.authenticate_user()

# import gspread
# from google.auth import default
# creds, _ = default()

# gc = gspread.authorize(creds)

import numpy as np
import pandas as pd

import os

import datetime 
from datetime import timedelta

In [2]:
#from google.colab import drive
#drive.mount('/content/drive')

In [3]:
#sht1 = gc.open_by_key('1H-BCDymP4yaJWiRuERi4kwv3ESa4GV8iEnvWMJeJT1s')
#sht1.share('lucasbetoni@bemol.com.br', perm_type='user', role='writer')

In [4]:
#Df = pd.read_excel('/content/drive/MyDrive/Bot_GM_Varejo/Base_GM_Varejo_Janeiro (1).xlsx')

#Df = pd.read_excel('/content/drive/MyDrive/Bot_GM_Varejo/Base_GM_Varejo_Fevereiro.xlsx')

#Df = pd.read_excel('/content/drive/MyDrive/Bot_GM_Varejo/Base_GM_Varejo_Março.xlsx')

#Df = pd.read_excel('/content/drive/MyDrive/Bot_GM_Varejo/Base_GM_Varejo_Abril.xlsx')

Dataframe = pd.read_excel('Base_Ficticia.xlsx')

In [6]:
Dataframe['GMarket'] = 0
Dataframe['GMarket'] = Dataframe['Grupo de mercadorias'].apply(lambda x: x[6:7])

In [7]:
Dataframe

,Organização vendas,Escritório de vendas,Centro,Fornecedor,Material,Grupo de mercadorias,Representante de vendas,Emissor da ordem,Condições pgto.,Data,Qtd.faturd,Qtd.faturd.1,Val.líq.,Val.líq..1,Imposto,Imposto.1,GMarket
0,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,184942 AR COND 7500BTUS SPRINGER Q...,117002001 JANELA ATÉ 8500 BTUS,00009999 VENDAS ON LINE,331136 NELMA ALVES ALVAREZ,C400 C400,27.04.2022,1,PEÇ,1252.00,BRL,0.00,BRL,0
1,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,184942 AR COND 7500BTUS SPRINGER Q...,117002001 JANELA ATÉ 8500 BTUS,00009999 VENDAS ON LINE,1981459 DIEGO LOPES DA SILVA,C400 C400,26.04.2022,1,PEÇ,1252.00,BRL,0.00,BRL,0
2,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,208442 SPLIT 12000 SPRINGER 42TFCA...,117008003 SPLIT 10001 À 18000,00009999 VENDAS ON LINE,1659086 JONAS CARDOSO,0001 0001,18.04.2022,1,PEÇ,1322.86,BRL,456.14,BRL,0
3,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,218672 MICRO-ONDAS MIDEA MXSA35S1 ...,117001008 FORNO MICRO-ONDAS,00007202 MICHELLE DOS SANTOS MONTEIRO,1311423 SHAYENE CAMPOS DE FREITAS,C400 C400,13.04.2022,1,PEÇ,649.82,BRL,0.00,BRL,0
4,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,218673 MICRO-ONDAS MIDEA MRAE21 20...,117001008 FORNO MICRO-ONDAS,00009999 VENDAS ON LINE,1034883 IVAN DA ROCHA CORREA,C400 C400,22.04.2022,1,PEÇ,513.84,BRL,0.00,BRL,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98350,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219808 PEIXE FILE DE PIRARUCU DUNO...,134001008 CONGELADOS,00009999 VENDAS ON LINE,3921132 RAYFRAN RODRIGUES DA SILVA,C200 C200,20.04.2022,2,PEÇ,74.44,BRL,16.34,BRL,0
98351,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,2078269 DAYNA TEREZA DA SILVA BEZERRA,C400 C400,11.04.2022,1,PEÇ,32.11,BRL,7.05,BRL,0
98352,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,2629200 AMANDA RIBEIRO MENDONCA,C400 C400,09.04.2022,1,PEÇ,31.28,BRL,6.87,BRL,0
98353,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,2665502 MARIA LAURA FARIAS DOS SANTOS,C400 C400,08.04.2022,1,PEÇ,29.64,BRL,6.51,BRL,0
98354,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,3940832 THAYNARA DA SILVA PIMENTEL,C400 C400,29.04.2022,1,PEÇ,31.28,BRL,6.87,BRL,0

In [ ]:
#worksheet = sht1.get_worksheet(1)

In [ ]:
#worksheet_list = sht1.worksheets()

In [ ]:
#worksheet_list

In [ ]:
#values_list = worksheet.row_values(1)
#values_list

## Tratando as Colunas

In [8]:
Dataframe2 = Dataframe.rename(columns={'Organização vendas': 'Org_vendas', 'Escritório de vendas': 'Escritorio_vendas', 'Centro': 'Centro', 'Fornecedor': 'Fornecedor',
'Material' : 'Material', 'Grupo de mercadorias' : 'Grupo_merc', 'Representante de vendas' : 'Representante_vendas', 'Condições pgto.' : 'Condicoes_pgto', 'Data' : 'Data', 'Qtd.faturd' : 'Qtd_faturd', 'Qtd.faturd.1' : 'Qtd_faturd1', 'Val.líq.' : 'Val_liq',
'Val.líq..1' : 'Val_liq1', 'Imposto' : 'Imposto', 'Imposto.1' : 'Imposto_1', 'GMarket' : 'GMarket'})

In [9]:
Dataframe2

,Org_vendas,Escritorio_vendas,Centro,Fornecedor,Material,Grupo_merc,Representante_vendas,Emissor da ordem,Condicoes_pgto,Data,Qtd_faturd,Qtd_faturd1,Val_liq,Val_liq1,Imposto,Imposto_1,GMarket
0,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,184942 AR COND 7500BTUS SPRINGER Q...,117002001 JANELA ATÉ 8500 BTUS,00009999 VENDAS ON LINE,331136 NELMA ALVES ALVAREZ,C400 C400,27.04.2022,1,PEÇ,1252.00,BRL,0.00,BRL,0
1,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,184942 AR COND 7500BTUS SPRINGER Q...,117002001 JANELA ATÉ 8500 BTUS,00009999 VENDAS ON LINE,1981459 DIEGO LOPES DA SILVA,C400 C400,26.04.2022,1,PEÇ,1252.00,BRL,0.00,BRL,0
2,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,208442 SPLIT 12000 SPRINGER 42TFCA...,117008003 SPLIT 10001 À 18000,00009999 VENDAS ON LINE,1659086 JONAS CARDOSO,0001 0001,18.04.2022,1,PEÇ,1322.86,BRL,456.14,BRL,0
3,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,218672 MICRO-ONDAS MIDEA MXSA35S1 ...,117001008 FORNO MICRO-ONDAS,00007202 MICHELLE DOS SANTOS MONTEIRO,1311423 SHAYENE CAMPOS DE FREITAS,C400 C400,13.04.2022,1,PEÇ,649.82,BRL,0.00,BRL,0
4,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,218673 MICRO-ONDAS MIDEA MRAE21 20...,117001008 FORNO MICRO-ONDAS,00009999 VENDAS ON LINE,1034883 IVAN DA ROCHA CORREA,C400 C400,22.04.2022,1,PEÇ,513.84,BRL,0.00,BRL,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98350,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219808 PEIXE FILE DE PIRARUCU DUNO...,134001008 CONGELADOS,00009999 VENDAS ON LINE,3921132 RAYFRAN RODRIGUES DA SILVA,C200 C200,20.04.2022,2,PEÇ,74.44,BRL,16.34,BRL,0
98351,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,2078269 DAYNA TEREZA DA SILVA BEZERRA,C400 C400,11.04.2022,1,PEÇ,32.11,BRL,7.05,BRL,0
98352,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,2629200 AMANDA RIBEIRO MENDONCA,C400 C400,09.04.2022,1,PEÇ,31.28,BRL,6.87,BRL,0
98353,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,2665502 MARIA LAURA FARIAS DOS SANTOS,C400 C400,08.04.2022,1,PEÇ,29.64,BRL,6.51,BRL,0
98354,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134001008 CONGELADOS,00009999 VENDAS ON LINE,3940832 THAYNARA DA SILVA PIMENTEL,C400 C400,29.04.2022,1,PEÇ,31.28,BRL,6.87,BRL,0

## Filtrando o Grupo_Mercadoria e Retirando vendas canceladas

In [10]:
Dataframe2['Grupo_merc'] = Dataframe2['Grupo_merc'].apply(lambda x: x[:3])

In [11]:
Dataframe2

,Org_vendas,Escritorio_vendas,Centro,Fornecedor,Material,Grupo_merc,Representante_vendas,Emissor da ordem,Condicoes_pgto,Data,Qtd_faturd,Qtd_faturd1,Val_liq,Val_liq1,Imposto,Imposto_1,GMarket
0,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,184942 AR COND 7500BTUS SPRINGER Q...,117,00009999 VENDAS ON LINE,331136 NELMA ALVES ALVAREZ,C400 C400,27.04.2022,1,PEÇ,1252.00,BRL,0.00,BRL,0
1,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,184942 AR COND 7500BTUS SPRINGER Q...,117,00009999 VENDAS ON LINE,1981459 DIEGO LOPES DA SILVA,C400 C400,26.04.2022,1,PEÇ,1252.00,BRL,0.00,BRL,0
2,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,208442 SPLIT 12000 SPRINGER 42TFCA...,117,00009999 VENDAS ON LINE,1659086 JONAS CARDOSO,0001 0001,18.04.2022,1,PEÇ,1322.86,BRL,456.14,BRL,0
3,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,218672 MICRO-ONDAS MIDEA MXSA35S1 ...,117,00007202 MICHELLE DOS SANTOS MONTEIRO,1311423 SHAYENE CAMPOS DE FREITAS,C400 C400,13.04.2022,1,PEÇ,649.82,BRL,0.00,BRL,0
4,0001 Org Vendas Amazonas,102 Online,101 101 - BEMOL S/A,137 CLIMAZON INDÚSTRIA LTDA,218673 MICRO-ONDAS MIDEA MRAE21 20...,117,00009999 VENDAS ON LINE,1034883 IVAN DA ROCHA CORREA,C400 C400,22.04.2022,1,PEÇ,513.84,BRL,0.00,BRL,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98350,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219808 PEIXE FILE DE PIRARUCU DUNO...,134,00009999 VENDAS ON LINE,3921132 RAYFRAN RODRIGUES DA SILVA,C200 C200,20.04.2022,2,PEÇ,74.44,BRL,16.34,BRL,0
98351,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134,00009999 VENDAS ON LINE,2078269 DAYNA TEREZA DA SILVA BEZERRA,C400 C400,11.04.2022,1,PEÇ,32.11,BRL,7.05,BRL,0
98352,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134,00009999 VENDAS ON LINE,2629200 AMANDA RIBEIRO MENDONCA,C400 C400,09.04.2022,1,PEÇ,31.28,BRL,6.87,BRL,0
98353,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134,00009999 VENDAS ON LINE,2665502 MARIA LAURA FARIAS DOS SANTOS,C400 C400,08.04.2022,1,PEÇ,29.64,BRL,6.51,BRL,0
98354,0001 Org Vendas Amazonas,102 Online,801 801 - BEMOL S/A,800000015 M V S COMÉRCIO DE PESCADOS EIRELI -,219810 PEIXE FILE DE ARUANA DUNORT...,134,00009999 VENDAS ON LINE,3940832 THAYNARA DA SILVA PIMENTEL,C400 C400,29.04.2022,1,PEÇ,31.28,BRL,6.87,BRL,0

In [12]:
Dataframe2['GMarket'].unique()

array(['0', '9'], dtype=object)

In [13]:
#new_df = df1.loc[df1['Val_liq']>0]

In [15]:
Dataframe3 = Dataframe2.drop(columns=['Org_vendas', 'Escritorio_vendas', 'Centro', 'Fornecedor', 'Material', 'Representante_vendas','Condicoes_pgto','Qtd_faturd','Qtd_faturd1','Val_liq1','Imposto_1'])

In [16]:
Dataframe3

,Grupo_merc,Emissor da ordem,Data,Val_liq,Imposto,GMarket
0,117,331136 NELMA ALVES ALVAREZ,27.04.2022,1252.00,0.00,0
1,117,1981459 DIEGO LOPES DA SILVA,26.04.2022,1252.00,0.00,0
2,117,1659086 JONAS CARDOSO,18.04.2022,1322.86,456.14,0
3,117,1311423 SHAYENE CAMPOS DE FREITAS,13.04.2022,649.82,0.00,0
4,117,1034883 IVAN DA ROCHA CORREA,22.04.2022,513.84,0.00,0
...,...,...,...,...,...,...
98350,134,3921132 RAYFRAN RODRIGUES DA SILVA,20.04.2022,74.44,16.34,0
98351,134,2078269 DAYNA TEREZA DA SILVA BEZERRA,11.04.2022,32.11,7.05,0
98352,134,2629200 AMANDA RIBEIRO MENDONCA,09.04.2022,31.28,6.87,0
98353,134,2665502 MARIA LAURA FARIAS DOS SANTOS,08.04.2022,29.64,6.51,0
98354,134,3940832 THAYNARA DA SILVA PIMENTEL,29.04.2022,31.28,6.87,0

## Calculando o Total (Liquido + Imposto)

In [17]:
Dataframe3

,Grupo_merc,Emissor da ordem,Data,Val_liq,Imposto,GMarket
0,117,331136 NELMA ALVES ALVAREZ,27.04.2022,1252.00,0.00,0
1,117,1981459 DIEGO LOPES DA SILVA,26.04.2022,1252.00,0.00,0
2,117,1659086 JONAS CARDOSO,18.04.2022,1322.86,456.14,0
3,117,1311423 SHAYENE CAMPOS DE FREITAS,13.04.2022,649.82,0.00,0
4,117,1034883 IVAN DA ROCHA CORREA,22.04.2022,513.84,0.00,0
...,...,...,...,...,...,...
98350,134,3921132 RAYFRAN RODRIGUES DA SILVA,20.04.2022,74.44,16.34,0
98351,134,2078269 DAYNA TEREZA DA SILVA BEZERRA,11.04.2022,32.11,7.05,0
98352,134,2629200 AMANDA RIBEIRO MENDONCA,09.04.2022,31.28,6.87,0
98353,134,2665502 MARIA LAURA FARIAS DOS SANTOS,08.04.2022,29.64,6.51,0
98354,134,3940832 THAYNARA DA SILVA PIMENTEL,29.04.2022,31.28,6.87,0

In [18]:
Dataframe4 = Dataframe3.eval('Total = Val_liq + Imposto')
Dataframe4

,Grupo_merc,Emissor da ordem,Data,Val_liq,Imposto,GMarket,Total
0,117,331136 NELMA ALVES ALVAREZ,27.04.2022,1252.00,0.00,0,1252.00
1,117,1981459 DIEGO LOPES DA SILVA,26.04.2022,1252.00,0.00,0,1252.00
2,117,1659086 JONAS CARDOSO,18.04.2022,1322.86,456.14,0,1779.00
3,117,1311423 SHAYENE CAMPOS DE FREITAS,13.04.2022,649.82,0.00,0,649.82
4,117,1034883 IVAN DA ROCHA CORREA,22.04.2022,513.84,0.00,0,513.84
...,...,...,...,...,...,...,...
98350,134,3921132 RAYFRAN RODRIGUES DA SILVA,20.04.2022,74.44,16.34,0,90.78
98351,134,2078269 DAYNA TEREZA DA SILVA BEZERRA,11.04.2022,32.11,7.05,0,39.16
98352,134,2629200 AMANDA RIBEIRO MENDONCA,09.04.2022,31.28,6.87,0,38.15
98353,134,2665502 MARIA LAURA FARIAS DOS SANTOS,08.04.2022,29.64,6.51,0,36.15
98354,134,3940832 THAYNARA DA SILVA PIMENTEL,29.04.2022,31.28,6.87,0,38.15

In [19]:
Dataframe5 = Dataframe4[['Data', 'Grupo_merc','GMarket','Val_liq','Imposto','Total']]

print(sorted(Dataframe5['Grupo_merc'].unique()))
print(sorted(Dataframe5['GMarket'].unique()))

['101', '102', '103', '104', '105', '107', '108', '109', '110', '111', '112', '113', '114', '115', '116', '117', '118', '119', '120', '123', '125', '126', '127', '128', '129', '130', '131', '132', '133', '134', '135', '136', '137']
['0', '9']

In [20]:
# df2_final = df1_final[['Data', 'Grupo_merc','Val_liq','Imposto','Total2']]

#sorted(df2_final['Grupo_merc'].unique())

In [21]:
Dataframe5.dtypes

Data           object
Grupo_merc     object
GMarket        object
Val_liq       float64
Imposto       float64
Total         float64
dtype: object

# Criação dos grupos de dados dos produtos normais e produtos de marketplace

In [22]:
groups2 = Dataframe5.groupby(Dataframe5.GMarket)

market = groups2.get_group('9')

groups = Dataframe5.groupby(Dataframe5.GMarket)

produtos = groups.get_group('0')

In [23]:
groups = produtos.groupby(produtos.Grupo_merc)

G101 = groups.get_group("101")
G102 = groups.get_group("102")
G103 = groups.get_group("103")
G104 = groups.get_group("104")
G105 = groups.get_group("105")
G107 = groups.get_group("107")
G108 = groups.get_group("108")
G109 = groups.get_group("109")
G110 = groups.get_group("110")
G111 = groups.get_group("111")
G112 = groups.get_group("112")
G113 = groups.get_group("113")
G114 = groups.get_group("114")
G115 = groups.get_group("115")
G116 = groups.get_group("116")
G117 = groups.get_group("117")
G118 = groups.get_group("118")
G119 = groups.get_group("119")
G120 = groups.get_group("120")
#G122 = groups.get_group("122")
G123 = groups.get_group("123")
G125 = groups.get_group("125")
G126 = groups.get_group("126")
G127 = groups.get_group("127")
G128 = groups.get_group("128")
G129 = groups.get_group("129")
G130 = groups.get_group("130")
G131 = groups.get_group("131")
G132 = groups.get_group("132")
G133 = groups.get_group("133")
G134 = groups.get_group("134")
#G135 = groups.get_group("135")
G136 = groups.get_group("136")
#G137 = groups.get_group("137")

In [24]:
groups2 = market.groupby(market.Grupo_merc)

#G103M = groups.get_group("103")
#G111M = groups.get_group("111")
#G113M = groups.get_group("113")
#G116M = groups.get_group("116")
G118M = groups2.get_group("118")
G119M = groups2.get_group("119")
G133M = groups2.get_group("133")
G135M = groups2.get_group("135")
G137M = groups2.get_group("137")

In [25]:
market['GMarket'].unique()

array(['9'], dtype=object)

MAP dos faturados

In [26]:
G101['Grupo_merc']=G101['Grupo_merc'].map('101 ARTIGOS INFANTIS'.format)
G102['Grupo_merc']=G102['Grupo_merc'].map('102 AUDIO'.format)
G103['Grupo_merc']=G103['Grupo_merc'].map('103 BAZAR'.format)
G104['Grupo_merc']=G104['Grupo_merc'].map('104 BICICLETA E MOTONETA'.format)
G105['Grupo_merc']=G105['Grupo_merc'].map('105 BRINQUEDOS'.format)
G107['Grupo_merc']=G107['Grupo_merc'].map('107 CAMA MESA E BANHO'.format)
G108['Grupo_merc']=G108['Grupo_merc'].map('108 CINE E FOTO'.format)
G109['Grupo_merc']=G109['Grupo_merc'].map('109 COLCHÕES'.format)
G110['Grupo_merc']=G110['Grupo_merc'].map('110 SAÚDE E BELEZA'.format)
G111['Grupo_merc']=G111['Grupo_merc'].map('111 ELETROPORTÁTEIS'.format)
G112['Grupo_merc']=G112['Grupo_merc'].map('112 ESCRITÓRIO'.format)
G113['Grupo_merc']=G113['Grupo_merc'].map('113 FAÇA VOCÊ MESMO'.format)
G114['Grupo_merc']=G114['Grupo_merc'].map('114 INFORMÁTICA'.format)
G115['Grupo_merc']=G115['Grupo_merc'].map('115 INSTRUMENTO MUSICAL'.format)
G116['Grupo_merc']=G116['Grupo_merc'].map('116 LAZER E ESPORTE'.format)
G117['Grupo_merc']=G117['Grupo_merc'].map('117 LINHA BRANCA'.format)
G118['Grupo_merc']=G118['Grupo_merc'].map('118 MÁQUINAS, MOTORES E PEÇAS'.format)
G119['Grupo_merc']=G119['Grupo_merc'].map('119 AUTOMOTIVO'.format)
G120['Grupo_merc']=G120['Grupo_merc'].map('120 MÓVEIS'.format)
#G122['Grupo_merc']=G122['Grupo_merc'].map('122 LIVROS'.format)
G123['Grupo_merc']=G123['Grupo_merc'].map('123 PRESENTE'.format)
G125['Grupo_merc']=G125['Grupo_merc'].map('125 RELÓGIO'.format)
G126['Grupo_merc']=G126['Grupo_merc'].map('126 TELEFONIA'.format)
G127['Grupo_merc']=G127['Grupo_merc'].map('127 UTILIDADE DOMÉSTICA'.format)
G128['Grupo_merc']=G128['Grupo_merc'].map('128 VOLTA ÀS AULAS'.format)
G129['Grupo_merc']=G129['Grupo_merc'].map('129 VIAGEM'.format)
G130['Grupo_merc']=G130['Grupo_merc'].map('130 VÍDEO'.format)
G131['Grupo_merc']=G131['Grupo_merc'].map('131 GAMERS'.format)
G132['Grupo_merc']=G132['Grupo_merc'].map('132 SMART HOME'.format)
G133['Grupo_merc']=G133['Grupo_merc'].map('133 PET SHOP'.format)
G134['Grupo_merc']=G134['Grupo_merc'].map('134 MERCADO'.format)
#G135['Grupo_merc']=G135['Grupo_merc'].map('135 MATERIAL DE CONSTRUÇÃO (MKT)'.format)
G136['Grupo_merc']=G136['Grupo_merc'].map('136 VEÍCULOS'.format)
#G137['Grupo_merc']=G137['Grupo_merc'].map('137 AGROPECUÁRIA (MKT)'.format)

C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G101['Grupo_merc']=G101['Grupo_merc'].map('101 ARTIGOS INFANTIS'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G102['Grupo_merc']=G102['Grupo_merc'].map('102 AUDIO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G103['Grupo_merc']=G103['Grupo_merc'].map('103 BAZAR'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G104['Grupo_merc']=G104['Grupo_merc'].map('104 BICICLETA E MOTONETA'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G105['Grupo_merc']=G105['Grupo_merc'].map('105 BRINQUEDOS'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G107['Grupo_merc']=G107['Grupo_merc'].map('107 CAMA MESA E BANHO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G108['Grupo_merc']=G108['Grupo_merc'].map('108 CINE E FOTO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G109['Grupo_merc']=G109['Grupo_merc'].map('109 COLCHÕES'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G110['Grupo_merc']=G110['Grupo_merc'].map('110 SAÚDE E BELEZA'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G111['Grupo_merc']=G111['Grupo_merc'].map('111 ELETROPORTÁTEIS'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G112['Grupo_merc']=G112['Grupo_merc'].map('112 ESCRITÓRIO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G113['Grupo_merc']=G113['Grupo_merc'].map('113 FAÇA VOCÊ MESMO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G114['Grupo_merc']=G114['Grupo_merc'].map('114 INFORMÁTICA'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G115['Grupo_merc']=G115['Grupo_merc'].map('115 INSTRUMENTO MUSICAL'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G116['Grupo_merc']=G116['Grupo_merc'].map('116 LAZER E ESPORTE'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G117['Grupo_merc']=G117['Grupo_merc'].map('117 LINHA BRANCA'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G118['Grupo_merc']=G118['Grupo_merc'].map('118 MÁQUINAS, MOTORES E PEÇAS'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G119['Grupo_merc']=G119['Grupo_merc'].map('119 AUTOMOTIVO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G120['Grupo_merc']=G120['Grupo_merc'].map('120 MÓVEIS'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G123['Grupo_merc']=G123['Grupo_merc'].map('123 PRESENTE'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G125['Grupo_merc']=G125['Grupo_merc'].map('125 RELÓGIO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G126['Grupo_merc']=G126['Grupo_merc'].map('126 TELEFONIA'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G127['Grupo_merc']=G127['Grupo_merc'].map('127 UTILIDADE DOMÉSTICA'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G128['Grupo_merc']=G128['Grupo_merc'].map('128 VOLTA ÀS AULAS'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G129['Grupo_merc']=G129['Grupo_merc'].map('129 VIAGEM'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G130['Grupo_merc']=G130['Grupo_merc'].map('130 VÍDEO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G131['Grupo_merc']=G131['Grupo_merc'].map('131 GAMERS'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G132['Grupo_merc']=G132['Grupo_merc'].map('132 SMART HOME'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G133['Grupo_merc']=G133['Grupo_merc'].map('133 PET SHOP'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G134['Grupo_merc']=G134['Grupo_merc'].map('134 MERCADO'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\1790758415.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G136['Grupo_merc']=G136['Grupo_merc'].map('136 VEÍCULOS'.format)

In [27]:

#G103M['Grupo_merc']=G103M['Grupo_merc'].map('103 BAZAR (MKT)'.format)
#G104['Grupo_merc']=G104['Grupo_merc'].map('104 BICICLETA E MOTONETA'.format)
#G105['Grupo_merc']=G105['Grupo_merc'].map('105 BRINQUEDOS'.format)
#G107['Grupo_merc']=G107['Grupo_merc'].map('107 CAMA MESA E BANHO'.format)
#G108['Grupo_merc']=G108['Grupo_merc'].map('108 CINE E FOTO'.format)
#G109['Grupo_merc']=G109['Grupo_merc'].map('109 COLCHÕES'.format)
#G110['Grupo_merc']=G110['Grupo_merc'].map('110 SAÚDE E BELEZA'.format)
#G111M['Grupo_merc']=G111M['Grupo_merc'].map('111 ELETROPORTÁTEIS (MKT)'.format)
#G112['Grupo_merc']=G112['Grupo_merc'].map('112 ESCRITÓRIO'.format)
#G113M['Grupo_merc']=G113M['Grupo_merc'].map('113 FAÇA VOCÊ MESMO (MKT)'.format)
#G114['Grupo_merc']=G114['Grupo_merc'].map('114 INFORMÁTICA'.format)
#G115['Grupo_merc']=G115['Grupo_merc'].map('115 INSTRUMENTO MUSICAL'.format)
#G116M['Grupo_merc']=G116M['Grupo_merc'].map('116 LAZER E ESPORTE (MKT)'.format)
#G117['Grupo_merc']=G117['Grupo_merc'].map('117 LINHA BRANCA'.format)
G118M['Grupo_merc']=G118M['Grupo_merc'].map('118 MÁQUINAS, MOTORES E PEÇAS (MKT)'.format)
G119M['Grupo_merc']=G119M['Grupo_merc'].map('119 AUTOMOTIVO (MKT)'.format)
#G120['Grupo_merc']=G120['Grupo_merc'].map('120 MÓVEIS'.format)
#G122['Grupo_merc']=G122['Grupo_merc'].map('122 LIVROS'.format)
#G123['Grupo_merc']=G123['Grupo_merc'].map('123 PRESENTE'.format)
#G125['Grupo_merc']=G125['Grupo_merc'].map('125 RELÓGIO'.format)
#G126['Grupo_merc']=G126['Grupo_merc'].map('126 TELEFONIA'.format)
#G127['Grupo_merc']=G127['Grupo_merc'].map('127 UTILIDADE DOMÉSTICA'.format)
#G128['Grupo_merc']=G128['Grupo_merc'].map('128 VOLTA ÀS AULAS'.format)
#G129['Grupo_merc']=G129['Grupo_merc'].map('129 VIAGEM'.format)
#G130['Grupo_merc']=G130['Grupo_merc'].map('130 VÍDEO'.format)
#G131['Grupo_merc']=G131['Grupo_merc'].map('131 GAMERS'.format)
#G132['Grupo_merc']=G132['Grupo_merc'].map('132 SMART HOME'.format)
G133M['Grupo_merc']=G133M['Grupo_merc'].map('133 PET SHOP (MKT)'.format)
#G134['Grupo_merc']=G134['Grupo_merc'].map('134 MERCADO'.format)
G135M['Grupo_merc']=G135M['Grupo_merc'].map('135 MATERIAL DE CONSTRUÇÃO (MKT)'.format)
#G136['Grupo_merc']=G136['Grupo_merc'].map('136 VEÍCULOS'.format)
G137M['Grupo_merc']=G137M['Grupo_merc'].map('137 AGROPECUÁRIA (MKT)'.format)

C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\3722279184.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G118M['Grupo_merc']=G118M['Grupo_merc'].map('118 MÁQUINAS, MOTORES E PEÇAS (MKT)'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\3722279184.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G119M['Grupo_merc']=G119M['Grupo_merc'].map('119 AUTOMOTIVO (MKT)'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\3722279184.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G133M['Grupo_merc']=G133M['Grupo_merc'].map('133 PET SHOP (MKT)'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\3722279184.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G135M['Grupo_merc']=G135M['Grupo_merc'].map('135 MATERIAL DE CONSTRUÇÃO (MKT)'.format)
C:\Users\juan.sousa\AppData\Local\Temp\ipykernel_17888\3722279184.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  G137M['Grupo_merc']=G137M['Grupo_merc'].map('137 AGROPECUÁRIA (MKT)'.format)

In [28]:
produtos1 = pd.concat([G101, G102, G103, G104, G105, G107, G108, G109, G110, G111, G112, G113, G114, G115, G116, G117, G118, G119, G120, G123, G125, G126, G127, G128, G129, G130, G131,G132, G133, G134, G136])
produtos2 = produtos1.reset_index(drop=True)
produtos2

             Data            Grupo_merc GMarket  Val_liq  Imposto   Total
0      11.04.2022  101 ARTIGOS INFANTIS       0   364.08    79.92   444.0
1      05.04.2022  101 ARTIGOS INFANTIS       0   326.36    71.64   398.0
2      30.04.2022  101 ARTIGOS INFANTIS       0   635.51   218.49   854.0
3      19.04.2022  101 ARTIGOS INFANTIS       0   130.38    28.62   159.0
4      21.04.2022  101 ARTIGOS INFANTIS       0   311.93    68.47   380.4
...           ...                   ...     ...      ...      ...     ...
93166  28.04.2022          136 VEÍCULOS       0  3147.16   690.84  3838.0
93167  30.04.2022          136 VEÍCULOS       0 -3147.16  -690.84 -3838.0
93168  27.04.2022          136 VEÍCULOS       0  2830.01   972.99  3803.0
93169  29.04.2022          136 VEÍCULOS       0  2856.05   981.95  3838.0
93170  27.04.2022          136 VEÍCULOS       0  2853.93   984.07  3838.0

[93171 rows x 6 columns]

In [29]:
market1 = pd.concat([G118M, G119M, G133M, G135M, G137M])
market2 = market1.reset_index(drop=True)
market2

,Data,Grupo_merc,GMarket,Val_liq,Imposto,Total
0,12.04.2022,"118 MÁQUINAS, MOTORES E PEÇAS (MKT)",9,346.04,75.96,422.00
1,22.04.2022,"118 MÁQUINAS, MOTORES E PEÇAS (MKT)",9,327.18,71.82,399.00
2,28.04.2022,"118 MÁQUINAS, MOTORES E PEÇAS (MKT)",9,327.18,71.82,399.00
3,12.04.2022,"118 MÁQUINAS, MOTORES E PEÇAS (MKT)",9,356.74,78.31,435.05
4,04.04.2022,"118 MÁQUINAS, MOTORES E PEÇAS (MKT)",9,328.91,113.09,442.00
...,...,...,...,...,...,...
5179,20.04.2022,137 AGROPECUÁRIA (MKT),9,21.58,4.74,26.32
5180,08.04.2022,137 AGROPECUÁRIA (MKT),9,19.68,4.32,24.00
5181,25.04.2022,137 AGROPECUÁRIA (MKT),9,23.78,5.22,29.00
5182,19.04.2022,137 AGROPECUÁRIA (MKT),9,41.82,9.18,51.00
5183,20.04.2022,137 AGROPECUÁRIA (MKT),9,14.14,4.86,19.00

In [30]:
ProdutoGeral = produtos2.merge(market2, how='outer')

In [31]:
ProdutoGeral

             Data              Grupo_merc GMarket  Val_liq  Imposto   Total
0      11.04.2022    101 ARTIGOS INFANTIS       0   364.08    79.92  444.00
1      05.04.2022    101 ARTIGOS INFANTIS       0   326.36    71.64  398.00
2      30.04.2022    101 ARTIGOS INFANTIS       0   635.51   218.49  854.00
3      19.04.2022    101 ARTIGOS INFANTIS       0   130.38    28.62  159.00
4      19.04.2022    101 ARTIGOS INFANTIS       0   130.38    28.62  159.00
...           ...                     ...     ...      ...      ...     ...
98350  08.04.2022  137 AGROPECUÁRIA (MKT)       9    19.68     4.32   24.00
98351  02.04.2022  137 AGROPECUÁRIA (MKT)       9    65.60    14.40   80.00
98352  20.04.2022  137 AGROPECUÁRIA (MKT)       9    21.58     4.74   26.32
98353  19.04.2022  137 AGROPECUÁRIA (MKT)       9    41.82     9.18   51.00
98354  20.04.2022  137 AGROPECUÁRIA (MKT)       9    14.14     4.86   19.00

[98355 rows x 6 columns]

# Soma Geral de todos os Grupos

In [32]:
Soma_total = ProdutoGeral['Total'].sum()

In [33]:
Soma_total

30289513.269999977

## Agrupamento dos dados através da "Grupo de Mercadoria" e contando a quantidade

In [34]:
#df_final2 = df_final1.groupby('Grupo_merc').sum()
#df_quant = df_final1['Grupo_merc'].value_counts().to_frame()
#df_quant.columns=['Quantidade']

In [35]:
df_quant2 = ProdutoGeral['Grupo_merc'].value_counts().to_frame()
df_quant2.columns=['Quantidade']

In [36]:
df_quant2

                                     Quantidade
134 MERCADO                               40193
127 UTILIDADE DOMÉSTICA                    8130
126 TELEFONIA                              6040
111 ELETROPORTÁTEIS                        5720
117 LINHA BRANCA                           5141
135 MATERIAL DE CONSTRUÇÃO (MKT)           4860
120 MÓVEIS                                 3928
110 SAÚDE E BELEZA                         2528
105 BRINQUEDOS                             2458
109 COLCHÕES                               2135
107 CAMA MESA E BANHO                      2082
114 INFORMÁTICA                            1946
102 AUDIO                                  1791
130 VÍDEO                                  1669
113 FAÇA VOCÊ MESMO                        1344
133 PET SHOP                               1324
125 RELÓGIO                                1317
116 LAZER E ESPORTE                         968
119 AUTOMOTIVO                              924
123 PRESENTE                                919
131 GAMERS                                  586
129 VIAGEM                                  485
101 ARTIGOS INFANTIS                        440
104 BICICLETA E MOTONETA                    374
128 VOLTA ÀS AULAS                          302
119 AUTOMOTIVO (MKT)                        167
132 SMART HOME                              111
115 INSTRUMENTO MUSICAL                      85
133 PET SHOP (MKT)                           80
118 MÁQUINAS, MOTORES E PEÇAS                75
112 ESCRITÓRIO                               63
137 AGROPECUÁRIA (MKT)                       63
103 BAZAR                                    49
136 VEÍCULOS                                 41
118 MÁQUINAS, MOTORES E PEÇAS (MKT)          14
108 CINE E FOTO                               3

In [37]:
df_final5 = ProdutoGeral.groupby('Grupo_merc').sum()
df_final5

                                        Val_liq    Imposto       Total
Grupo_merc
101 ARTIGOS INFANTIS                  115699.79   26776.88   142476.67
102 AUDIO                             542754.57   34125.25   576879.82
103 BAZAR                               1446.20     203.11     1649.31
104 BICICLETA E MOTONETA              191440.77   52006.28   243447.05
105 BRINQUEDOS                        253370.42   63091.29   316461.71
107 CAMA MESA E BANHO                 214924.33   54191.42   269115.75
108 CINE E FOTO                         7839.60    2217.40    10057.00
109 COLCHÕES                         1033254.88  166392.55  1199647.43
110 SAÚDE E BELEZA                    473769.50   22900.60   496670.10
111 ELETROPORTÁTEIS                  1429296.67   68179.38  1497476.05
112 ESCRITÓRIO                          5727.07    1203.00     6930.07
113 FAÇA VOCÊ MESMO                   356661.14   80950.15   437611.29
114 INFORMÁTICA                      1520144.23  116047.20  1636191.43
115 INSTRUMENTO MUSICAL                31932.82    8189.76    40122.58
116 LAZER E ESPORTE                   176052.15   42272.17   218324.32
117 LINHA BRANCA                     6359361.20  347895.02  6707256.22
118 MÁQUINAS, MOTORES E PEÇAS          82397.96   19157.36   101555.32
118 MÁQUINAS, MOTORES E PEÇAS (MKT)     5872.30    1408.91     7281.21
119 AUTOMOTIVO                        319562.95   11818.65   331381.60
119 AUTOMOTIVO (MKT)                  124373.91    9219.95   133593.86
120 MÓVEIS                           2115209.15  473419.35  2588628.50
123 PRESENTE                           78644.04    7604.10    86248.14
125 RELÓGIO                           247101.48   54701.00   301802.48
126 TELEFONIA                        7058023.60  379937.17  7437960.77
127 UTILIDADE DOMÉSTICA               704026.04  142216.70   846242.74
128 VOLTA ÀS AULAS                      6089.72    1183.15     7272.87
129 VIAGEM                            106126.54   21706.13   127832.67
130 VÍDEO                            1844128.27  108531.52  1952659.79
131 GAMERS                            283116.57   22041.42   305157.99
132 SMART HOME                         27088.66    1285.03    28373.69
133 PET SHOP                          156353.80    6973.45   163327.25
133 PET SHOP (MKT)                      7407.56    1522.81     8930.37
134 MERCADO                          1146268.09   63441.37  1209709.46
135 MATERIAL DE CONSTRUÇÃO (MKT)      648342.37   54045.11   702387.48
136 VEÍCULOS                          108075.56   36937.26   145012.82
137 AGROPECUÁRIA (MKT)                  3020.39     817.07     3837.46

In [38]:
df_p1 = (df_final5['Total'] / Soma_total).to_frame()
df_p1.columns=['Percentual']

In [39]:
df_final5

                                        Val_liq    Imposto       Total
Grupo_merc
101 ARTIGOS INFANTIS                  115699.79   26776.88   142476.67
102 AUDIO                             542754.57   34125.25   576879.82
103 BAZAR                               1446.20     203.11     1649.31
104 BICICLETA E MOTONETA              191440.77   52006.28   243447.05
105 BRINQUEDOS                        253370.42   63091.29   316461.71
107 CAMA MESA E BANHO                 214924.33   54191.42   269115.75
108 CINE E FOTO                         7839.60    2217.40    10057.00
109 COLCHÕES                         1033254.88  166392.55  1199647.43
110 SAÚDE E BELEZA                    473769.50   22900.60   496670.10
111 ELETROPORTÁTEIS                  1429296.67   68179.38  1497476.05
112 ESCRITÓRIO                          5727.07    1203.00     6930.07
113 FAÇA VOCÊ MESMO                   356661.14   80950.15   437611.29
114 INFORMÁTICA                      1520144.23  116047.20  1636191.43
115 INSTRUMENTO MUSICAL                31932.82    8189.76    40122.58
116 LAZER E ESPORTE                   176052.15   42272.17   218324.32
117 LINHA BRANCA                     6359361.20  347895.02  6707256.22
118 MÁQUINAS, MOTORES E PEÇAS          82397.96   19157.36   101555.32
118 MÁQUINAS, MOTORES E PEÇAS (MKT)     5872.30    1408.91     7281.21
119 AUTOMOTIVO                        319562.95   11818.65   331381.60
119 AUTOMOTIVO (MKT)                  124373.91    9219.95   133593.86
120 MÓVEIS                           2115209.15  473419.35  2588628.50
123 PRESENTE                           78644.04    7604.10    86248.14
125 RELÓGIO                           247101.48   54701.00   301802.48
126 TELEFONIA                        7058023.60  379937.17  7437960.77
127 UTILIDADE DOMÉSTICA               704026.04  142216.70   846242.74
128 VOLTA ÀS AULAS                      6089.72    1183.15     7272.87
129 VIAGEM                            106126.54   21706.13   127832.67
130 VÍDEO                            1844128.27  108531.52  1952659.79
131 GAMERS                            283116.57   22041.42   305157.99
132 SMART HOME                         27088.66    1285.03    28373.69
133 PET SHOP                          156353.80    6973.45   163327.25
133 PET SHOP (MKT)                      7407.56    1522.81     8930.37
134 MERCADO                          1146268.09   63441.37  1209709.46
135 MATERIAL DE CONSTRUÇÃO (MKT)      648342.37   54045.11   702387.48
136 VEÍCULOS                          108075.56   36937.26   145012.82
137 AGROPECUÁRIA (MKT)                  3020.39     817.07     3837.46

## Unindo os Dataframes para visualização final e Exportando o Arquivo

Faturados

In [40]:
DataF2 = df_final5.join(df_quant2, on ='Grupo_merc', how = 'left')
DataF3 = DataF2.join(df_p1, on ='Grupo_merc', how = 'left')

DataF3 = DataF3[['Quantidade','Total','Percentual']]

Final = DataF3.reset_index(drop=False)

Final

                             Grupo_merc  Quantidade       Total  Percentual
0                  101 ARTIGOS INFANTIS         440   142476.67    0.004704
1                             102 AUDIO        1791   576879.82    0.019046
2                             103 BAZAR          49     1649.31    0.000054
3              104 BICICLETA E MOTONETA         374   243447.05    0.008037
4                        105 BRINQUEDOS        2458   316461.71    0.010448
5                 107 CAMA MESA E BANHO        2082   269115.75    0.008885
6                       108 CINE E FOTO           3    10057.00    0.000332
7                          109 COLCHÕES        2135  1199647.43    0.039606
8                    110 SAÚDE E BELEZA        2528   496670.10    0.016397
9                   111 ELETROPORTÁTEIS        5720  1497476.05    0.049439
10                       112 ESCRITÓRIO          63     6930.07    0.000229
11                  113 FAÇA VOCÊ MESMO        1344   437611.29    0.014448
12                      114 INFORMÁTICA        1946  1636191.43    0.054018
13              115 INSTRUMENTO MUSICAL          85    40122.58    0.001325
14                  116 LAZER E ESPORTE         968   218324.32    0.007208
15                     117 LINHA BRANCA        5141  6707256.22    0.221438
16        118 MÁQUINAS, MOTORES E PEÇAS          75   101555.32    0.003353
17  118 MÁQUINAS, MOTORES E PEÇAS (MKT)          14     7281.21    0.000240
18                       119 AUTOMOTIVO         924   331381.60    0.010940
19                 119 AUTOMOTIVO (MKT)         167   133593.86    0.004411
20                           120 MÓVEIS        3928  2588628.50    0.085463
21                         123 PRESENTE         919    86248.14    0.002847
22                          125 RELÓGIO        1317   301802.48    0.009964
23                        126 TELEFONIA        6040  7437960.77    0.245562
24              127 UTILIDADE DOMÉSTICA        8130   846242.74    0.027938
25                   128 VOLTA ÀS AULAS         302     7272.87    0.000240
26                           129 VIAGEM         485   127832.67    0.004220
27                            130 VÍDEO        1669  1952659.79    0.064467
28                           131 GAMERS         586   305157.99    0.010075
29                       132 SMART HOME         111    28373.69    0.000937
30                         133 PET SHOP        1324   163327.25    0.005392
31                   133 PET SHOP (MKT)          80     8930.37    0.000295
32                          134 MERCADO       40193  1209709.46    0.039938
33     135 MATERIAL DE CONSTRUÇÃO (MKT)        4860   702387.48    0.023189
34                         136 VEÍCULOS          41   145012.82    0.004788
35               137 AGROPECUÁRIA (MKT)          63     3837.46    0.000127

In [41]:
Final.to_excel("Dados_Market_Abril_final.xlsx")